[build]
  base = "portfolio/frontend" # Le répertoire racine de votre projet React
  command = "npm run build" # La commande de build pour créer les fichiers statiques
  publish = "build" # Le répertoire où se trouvent les fichiers à publier
